spring:
  application:
    name: exchange-user
  datasource:
    url: jdbc:mysql://localhost:3306/exchange-users?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update


server.port: 3000

eureka:
  instance:
    appname: ${spring.application.name}

