spring:
  cloud:
    gateway:
      routes:
        - id: exchange-users
          uri: http://localhost:3000
          predicates:
          - Path=/users

        - id: exchange-accounts
          uri: http://localhost:4000
          predicates:
          - Path=/accounts

        - id: exchange-orders
          uri: http://localhost:5000
          predicates:
          - Path=/orders

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG

management.endpoints.web.exposure.include: '*'
server:
  port: 2000

